import { AssetItem, StructuralCategory } from '../types';

export const STRUCTURAL_CATEGORIES: { id: StructuralCategory; label: string; icon: string; description: string }[] = [
  { id: 'code', label: 'Code & Object-Oriented', icon: 'Box', description: 'Classes, interfaces, structs, enums, protocols, maps' },
  { id: 'component', label: 'Component & Modular', icon: 'Cpu', description: 'Components, ports, lollipops, collections, robustness' },
  { id: 'infrastructure', label: 'Infrastructure & Hardware', icon: 'Server', description: 'Node 3D, database, storage, cloud, queue, stack, hexagon' },
  { id: 'data-schema', label: 'Data, Schema & Dictionary', icon: 'Database', description: 'Relational entity tables, JSON, YAML, dictionary maps' },
  { id: 'container', label: 'Boundary & Grouping', icon: 'Folder', description: 'Packages, namespaces, frames, folders, subnets' },
  { id: 'activity-state', label: 'Activity & State Workflow', icon: 'GitCommit', description: 'Start, stop, actions, decisions, forks, states, use cases' },
  { id: 'actor-agent', label: 'Actors, People & Agents', icon: 'Users', description: 'Actors, wire actors, bots, agents, boundary gateways' },
  { id: 'c4', label: 'C4 Architecture Model', icon: 'Layers', description: 'Person, System, Container, Component, Deployment' },
  { id: 'archimate', label: 'ArchiMate Enterprise', icon: 'Layers', description: 'Business, Application, Technology, and Strategy layers' },
  { id: 'domainstory', label: 'Domain Storytelling', icon: 'BookOpen', description: 'Domain storytelling actors, work objects, activities, conversations' },
  { id: 'adaml', label: 'AdaML Architecture', icon: 'Code', description: 'Ada packages, subprograms, bodies, tasks, dependencies' },
  { id: 'cloud', label: 'Cloud Infrastructure Libs', icon: 'Cloud', description: 'AWS, GCP, Azure, and Kubernetes standard nodes' },
  { id: 'embedded', label: 'Embedded Sub-Engines', icon: 'Code', description: 'Salt wireframes, Ditaa ASCII art, LaTeX formulas' },
  { id: 'annotation', label: 'Annotations & Notes', icon: 'FileText', description: 'Directional sticky notes, link annotations, legends' },
  { id: 'sequence', label: 'Sequence & Interactions', icon: 'ArrowLeftRight', description: 'Lifelines, participants, synchronous calls, returns, async events, alt/loop frames' }
];

export const UNIFIED_ASSETS: AssetItem[] = [
  // ==================== 1. CODE & OBJECT-ORIENTED ====================
  {
    id: 'code-class',
    label: 'Class',
    nodeType: 'class',
    icon: 'Box',
    category: 'code',
    categoryLabel: 'Code & Object-Oriented',
    description: 'UML class with fields, methods and visibility indicators',
    plantumlKeyword: 'class',
    defaultColor: 'sienna',
    width: 220,
    height: 150,
    shape: 'rectangle',
    defaultData: {
      spot: { character: 'C', colorHex: '#2e7d32' },
      attributes: ['+id: Long', '-secretKey: String', '#state: State'],
      methods: ['+save(): boolean', '+find(id): Entity', '{static} +builder(): Builder']
    }
  },
  {
    id: 'code-abstract',
    label: 'Abstract Class',
    nodeType: 'abstract-class',
    icon: 'FileCode',
    category: 'code',
    categoryLabel: 'Code & Object-Oriented',
    description: 'Base class with abstract methods',
    plantumlKeyword: 'abstract class',
    defaultColor: 'terracotta',
    width: 220,
    height: 130,
    sublabel: '<<abstract>>',
    shape: 'rectangle',
    defaultData: {
      spot: { character: 'A', colorHex: '#f59e0b' },
      isAbstract: true,
      attributes: ['#baseConfig: Config'],
      methods: ['{abstract} +execute(): void', '+logEvent(): void']
    }
  },
  {
    id: 'code-interface',
    label: 'Interface',
    nodeType: 'interface',
    icon: 'Radio',
    category: 'code',
    categoryLabel: 'Code & Object-Oriented',
    description: 'Contract interface specification',
    plantumlKeyword: 'interface',
    defaultColor: 'sage',
    width: 210,
    height: 120,
    sublabel: '<<interface>>',
    shape: 'rectangle',
    defaultData: {
      spot: { character: 'I', colorHex: '#7c3aed' },
      generics: '<T>',
      methods: ['+process(item: T): Result', '+healthCheck(): boolean']
    }
  },
  {
    id: 'code-enum',
    label: 'Enum',
    nodeType: 'enum',
    icon: 'ListFilter',
    category: 'code',
    categoryLabel: 'Code & Object-Oriented',
    description: 'Enumeration of constant values',
    plantumlKeyword: 'enum',
    defaultColor: 'sand',
    width: 170,
    height: 120,
    sublabel: '<<enum>>',
    shape: 'rectangle',
    defaultData: {
      spot: { character: 'E', colorHex: '#d97706' },
      attributes: ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED']
    }
  },
  {
    id: 'code-struct',
    label: 'Struct',
    nodeType: 'struct',
    icon: 'Box',
    category: 'code',
    categoryLabel: 'Code & Object-Oriented',
    description: 'C/Go/Rust memory data structure',
    plantumlKeyword: 'struct',
    defaultColor: 'sienna',
    width: 190,
    height: 110,
    sublabel: '<<struct>>',
    shape: 'rectangle',
    defaultData: {
      attributes: ['+x: double', '+y: double', '+z: double']
    }
  },
  {
    id: 'code-protocol',
    label: 'Protocol',
    nodeType: 'protocol',
    icon: 'Radio',
    category: 'code',
    categoryLabel: 'Code & Object-Oriented',
    description: 'Formal protocol contract (Swift, Python)',
    plantumlKeyword: 'protocol',
    defaultColor: 'sage',
    width: 200,
    height: 110,
    sublabel: '<<protocol>>',
    shape: 'rectangle',
    defaultData: {
      methods: ['+serialize(): bytes', '+deserialize(data): self']
    }
  },
  {
    id: 'code-exception',
    label: 'Exception',
    nodeType: 'exception',
    icon: 'FileCode',
    category: 'code',
    categoryLabel: 'Code & Object-Oriented',
    description: 'Error and exception classifier',
    plantumlKeyword: 'exception',
    defaultColor: 'terracotta',
    width: 210,
    height: 110,
    sublabel: '<<exception>>',
    shape: 'rectangle',
    defaultData: {
      attributes: ['-errorCode: Integer', '+message: String']
    }
  },
  {
    id: 'code-object',
    label: 'Object Instance',
    nodeType: 'object',
    icon: 'FileText',
    category: 'code',
    categoryLabel: 'Code & Object-Oriented',
    description: 'Concrete runtime object with fixed slot values',
    plantumlKeyword: 'object',
    defaultColor: 'ochre',
    width: 210,
    height: 120,
    shape: 'rectangle',
    defaultData: {
      className: 'UserSession',
      slots: [
        { key: 'userId', value: '"usr_9812"' },
        { key: 'token', value: '"eyJhbGci..."' },
        { key: 'role', value: '"ADMIN"' }
      ]
    }
  },
  {
    id: 'code-map',
    label: 'Map Dictionary',
    nodeType: 'map',
    icon: 'ListFilter',
    category: 'code',
    categoryLabel: 'Code & Object-Oriented',
    description: 'Associative key-value dictionary table',
    plantumlKeyword: 'map',
    defaultColor: 'sand',
    width: 210,
    height: 120,
    shape: 'rectangle',
    defaultData: {
      mapEntries: [
        { key: 'timeout', value: '30s' },
        { key: 'retries', value: '3' },
        { key: 'debug', value: 'true' }
      ]
    }
  },

  // ==================== 2. COMPONENT & MODULAR ====================
  {
    id: 'comp-standard',
    label: 'Component',
    nodeType: 'component',
    icon: 'Cpu',
    category: 'component',
    categoryLabel: 'Component & Modular',
    description: 'Independent software module or microservice',
    plantumlKeyword: 'component',
    defaultColor: 'sienna',
    width: 180,
    height: 80,
    shape: 'component',
    defaultData: {
      ports: [
        { id: 'p1', name: 'http', position: 'left', type: 'in' },
        { id: 'p2', name: 'grpc', position: 'right', type: 'out' }
      ]
    }
  },
  {
    id: 'comp-lollipop',
    label: 'Lollipop Interface',
    nodeType: 'interface-lollipop',
    icon: 'CircleDot',
    category: 'component',
    categoryLabel: 'Component & Modular',
    description: 'Circular lollipop contract socket',
    plantumlKeyword: '()',
    defaultColor: 'sand',
    width: 120,
    height: 60,
    shape: 'lollipop',
    defaultData: {}
  },
  {
    id: 'comp-collections',
    label: 'Worker Collections',
    nodeType: 'collections',
    icon: 'Layers',
    category: 'component',
    categoryLabel: 'Component & Modular',
    description: 'Cascading offset boxes for worker replicas or pools',
    plantumlKeyword: 'collections',
    defaultColor: 'slate',
    width: 190,
    height: 90,
    shape: 'collections',
    defaultData: {}
  },
  {
    id: 'comp-boundary',
    label: 'Boundary Gateway',
    nodeType: 'boundary',
    icon: 'Radio',
    category: 'component',
    categoryLabel: 'Component & Modular',
    description: 'Robustness analysis presentation gateway',
    plantumlKeyword: 'boundary',
    defaultColor: 'sand',
    width: 160,
    height: 80,
    shape: 'boundary',
    defaultData: {}
  },
  {
    id: 'comp-control',
    label: 'Control Logic',
    nodeType: 'control',
    icon: 'RotateCcw',
    category: 'component',
    categoryLabel: 'Component & Modular',
    description: 'Robustness analysis process/workflow controller',
    plantumlKeyword: 'control',
    defaultColor: 'terracotta',
    width: 160,
    height: 80,
    shape: 'control',
    defaultData: {}
  },
  {
    id: 'comp-entity-circle',
    label: 'Domain Entity',
    nodeType: 'entity-circle',
    icon: 'CircleDot',
    category: 'component',
    categoryLabel: 'Component & Modular',
    description: 'Robustness persistent entity circle',
    plantumlKeyword: 'entity',
    defaultColor: 'ochre',
    width: 160,
    height: 80,
    shape: 'entity-circle',
    defaultData: {}
  },

  // ==================== 3. INFRASTRUCTURE & HARDWARE ====================
  {
    id: 'infra-node3d',
    label: 'Compute Node (3D Cube)',
    nodeType: 'node',
    icon: 'Server',
    category: 'infrastructure',
    categoryLabel: 'Infrastructure & Hardware',
    description: '3D isometric cube bare-metal server / VM host',
    plantumlKeyword: 'node',
    defaultColor: 'slate',
    width: 190,
    height: 90,
    shape: 'node3d',
    defaultData: {}
  },
  {
    id: 'infra-database',
    label: 'Database Cylinder',
    nodeType: 'database',
    icon: 'Database',
    category: 'infrastructure',
    categoryLabel: 'Infrastructure & Hardware',
    description: '3D vertical datastore cylinder',
    plantumlKeyword: 'database',
    defaultColor: 'ochre',
    width: 180,
    height: 90,
    shape: 'cylinder',
    defaultData: {}
  },
  {
    id: 'infra-storage',
    label: 'Storage Block',
    nodeType: 'storage',
    icon: 'HardDrive',
    category: 'infrastructure',
    categoryLabel: 'Infrastructure & Hardware',
    description: 'Horizontal storage cylinder / object store (S3, Ceph)',
    plantumlKeyword: 'storage',
    defaultColor: 'sand',
    width: 180,
    height: 80,
    shape: 'horiz-cylinder',
    defaultData: {}
  },
  {
    id: 'infra-cloud',
    label: 'Cloud Perimeter',
    nodeType: 'cloud',
    icon: 'Cloud',
    category: 'infrastructure',
    categoryLabel: 'Infrastructure & Hardware',
    description: 'Fluffy cloud outline for WAN / SaaS / VPC',
    plantumlKeyword: 'cloud',
    defaultColor: 'sage',
    width: 200,
    height: 100,
    shape: 'cloud',
    defaultData: {}
  },
  {
    id: 'infra-queue',
    label: 'Message Queue',
    nodeType: 'queue',
    icon: 'Radio',
    category: 'infrastructure',
    categoryLabel: 'Infrastructure & Hardware',
    description: 'Horizontal cylindrical message broker pipe (Kafka, SQS)',
    plantumlKeyword: 'queue',
    defaultColor: 'terracotta',
    width: 190,
    height: 70,
    shape: 'queue',
    defaultData: {}
  },
  {
    id: 'infra-stack',
    label: 'Stack Buffer',
    nodeType: 'stack',
    icon: 'Layers',
    category: 'infrastructure',
    categoryLabel: 'Infrastructure & Hardware',
    description: 'Call stack or layered middleware memory buffer',
    plantumlKeyword: 'stack',
    defaultColor: 'slate',
    width: 170,
    height: 90,
    shape: 'stack',
    defaultData: {}
  },
  {
    id: 'infra-artifact',
    label: 'Artifact Binary',
    nodeType: 'artifact',
    icon: 'FileCode',
    category: 'infrastructure',
    categoryLabel: 'Infrastructure & Hardware',
    description: 'Deployable binary (Docker image, JAR, executable)',
    plantumlKeyword: 'artifact',
    defaultColor: 'sand',
    width: 170,
    height: 80,
    shape: 'artifact',
    defaultData: {}
  },
  {
    id: 'infra-file',
    label: 'Config File',
    nodeType: 'file',
    icon: 'FileText',
    category: 'infrastructure',
    categoryLabel: 'Infrastructure & Hardware',
    description: 'Document page with folded corner (.yaml, .env)',
    plantumlKeyword: 'file',
    defaultColor: 'sand',
    width: 160,
    height: 80,
    shape: 'file',
    defaultData: {}
  },
  {
    id: 'infra-folder',
    label: 'Folder Directory',
    nodeType: 'folder',
    icon: 'Folder',
    category: 'infrastructure',
    categoryLabel: 'Infrastructure & Hardware',
    description: 'Tabbed filesystem directory',
    plantumlKeyword: 'folder',
    defaultColor: 'sand',
    width: 180,
    height: 90,
    shape: 'folder',
    defaultData: {}
  },
  {
    id: 'infra-frame',
    label: 'Window Frame',
    nodeType: 'frame',
    icon: 'Maximize2',
    category: 'infrastructure',
    categoryLabel: 'Infrastructure & Hardware',
    description: 'Application execution window frame',
    plantumlKeyword: 'frame',
    defaultColor: 'slate',
    width: 190,
    height: 100,
    shape: 'frame',
    defaultData: {}
  },
  {
    id: 'infra-card',
    label: 'Card Header',
    nodeType: 'card',
    icon: 'CreditCard',
    category: 'infrastructure',
    categoryLabel: 'Infrastructure & Hardware',
    description: 'Flat border card with header',
    plantumlKeyword: 'card',
    defaultColor: 'sand',
    width: 180,
    height: 80,
    shape: 'card',
    defaultData: {}
  },
  {
    id: 'infra-hexagon',
    label: 'Hexagon Adapter',
    nodeType: 'hexagon',
    icon: 'Hexagon',
    category: 'infrastructure',
    categoryLabel: 'Infrastructure & Hardware',
    description: '6-sided hexagon for ports & adapters architecture',
    plantumlKeyword: 'hexagon',
    defaultColor: 'ochre',
    width: 180,
    height: 100,
    shape: 'hexagon',
    defaultData: {}
  },

  // ==================== 4. DATA, SCHEMA & DICTIONARY ====================
  {
    id: 'data-er',
    label: 'Relational Entity (ER)',
    nodeType: 'entity',
    icon: 'Database',
    category: 'data-schema',
    categoryLabel: 'Data, Schema & Dictionary',
    description: 'Database table with PK/FK columns and Crow\'s Foot cardinality',
    plantumlKeyword: 'entity',
    defaultColor: 'ochre',
    width: 230,
    height: 160,
    sublabel: '<<entity>>',
    shape: 'rectangle',
    defaultData: {
      tableName: 'orders',
      columns: [
        { name: 'id', type: 'bigint', isPk: true },
        { name: 'customer_id', type: 'bigint', isFk: true },
        { name: 'total_cents', type: 'integer' },
        { name: 'status', type: 'varchar(32)' }
      ]
    }
  },
  {
    id: 'data-json',
    label: 'Interactive JSON Tree',
    nodeType: 'data-json',
    icon: 'Code',
    category: 'data-schema',
    categoryLabel: 'Data, Schema & Dictionary',
    description: 'Live formatted JSON payload node',
    plantumlKeyword: 'json',
    defaultColor: 'sand',
    width: 230,
    height: 150,
    shape: 'rectangle',
    defaultData: {
      treeFormat: 'json',
      treeContent: '{\n  "service": "billing",\n  "port": 8080,\n  "enabled": true\n}'
    }
  },
  {
    id: 'data-yaml',
    label: 'YAML Configuration',
    nodeType: 'data-yaml',
    icon: 'FileText',
    category: 'data-schema',
    categoryLabel: 'Data, Schema & Dictionary',
    description: 'Hierarchical YAML deployment configuration',
    plantumlKeyword: 'yaml',
    defaultColor: 'sand',
    width: 230,
    height: 150,
    shape: 'rectangle',
    defaultData: {
      treeFormat: 'yaml',
      treeContent: 'apiVersion: v1\nkind: Service\nmetadata:\n  name: auth-svc'
    }
  },

  // ==================== 5. BOUNDARY & GROUPING ====================
  {
    id: 'group-package',
    label: 'Package Namespace',
    nodeType: 'package',
    icon: 'Folder',
    category: 'container',
    categoryLabel: 'Boundary & Grouping',
    description: 'Standard UML folder-tab namespace perimeter',
    plantumlKeyword: 'package',
    defaultColor: 'sand',
    width: 260,
    height: 180,
    shape: 'package',
    defaultData: { isContainer: true, containerType: 'package' }
  },
  {
    id: 'group-rectangle',
    label: 'Subsystem Perimeter',
    nodeType: 'rectangle',
    icon: 'Maximize2',
    category: 'container',
    categoryLabel: 'Boundary & Grouping',
    description: 'Clean boundary perimeter enclosing microservices',
    plantumlKeyword: 'rectangle',
    defaultColor: 'slate',
    width: 260,
    height: 180,
    shape: 'rectangle',
    defaultData: { isContainer: true, containerType: 'rectangle' }
  },

  // ==================== 5B. ACTIVITY & STATE WORKFLOW ====================
  {
    id: 'act-start',
    label: 'Start State (*)',
    nodeType: 'activity-start',
    icon: 'Circle',
    category: 'activity-state',
    categoryLabel: 'Activity & State Workflow',
    description: 'Activity start / initial pseudo-state (*)',
    plantumlKeyword: 'start',
    defaultColor: 'slate',
    width: 32,
    height: 32,
    shape: 'start',
    defaultData: {}
  },
  {
    id: 'act-stop',
    label: 'End / Stop State (*)',
    nodeType: 'activity-stop',
    icon: 'Disc',
    category: 'activity-state',
    categoryLabel: 'Activity & State Workflow',
    description: 'Activity stop / final state bullseye',
    plantumlKeyword: 'stop',
    defaultColor: 'slate',
    width: 34,
    height: 34,
    shape: 'stop',
    defaultData: {}
  },
  {
    id: 'act-decision',
    label: 'Decision / Branch',
    nodeType: 'activity-decision',
    icon: 'HelpCircle',
    category: 'activity-state',
    categoryLabel: 'Activity & State Workflow',
    description: 'Conditional decision diamond (if/then/else)',
    plantumlKeyword: 'if',
    defaultColor: 'sand',
    width: 110,
    height: 64,
    shape: 'diamond',
    defaultData: {}
  },
  {
    id: 'act-fork',
    label: 'Fork / Join Sync Bar',
    nodeType: 'activity-fork',
    icon: 'Minus',
    category: 'activity-state',
    categoryLabel: 'Activity & State Workflow',
    description: 'Concurrent fork or join synchronization bar',
    plantumlKeyword: 'fork',
    defaultColor: 'slate',
    width: 130,
    height: 10,
    shape: 'sync-bar',
    defaultData: {}
  },
  {
    id: 'act-flow-final',
    label: 'Flow Final (Circle X)',
    nodeType: 'activity-flow-final',
    icon: 'XCircle',
    category: 'activity-state',
    categoryLabel: 'Activity & State Workflow',
    description: 'Activity flow final node terminating one branch',
    plantumlKeyword: 'circle <<flowfinal>>',
    defaultColor: 'slate',
    width: 32,
    height: 32,
    defaultData: {}
  },
  {
    id: 'act-state-history',
    label: 'History State [H]',
    nodeType: 'state-history',
    icon: 'RotateCcw',
    category: 'activity-state',
    categoryLabel: 'Activity & State Workflow',
    description: 'Shallow state history resume pseudo-state',
    plantumlKeyword: 'state "[H]"',
    defaultColor: 'sand',
    width: 34,
    height: 34,
    defaultData: { isDeep: false }
  },
  {
    id: 'act-state-deep-history',
    label: 'Deep History [H*]',
    nodeType: 'state-history',
    icon: 'History',
    category: 'activity-state',
    categoryLabel: 'Activity & State Workflow',
    description: 'Deep hierarchical state history resume pseudo-state',
    plantumlKeyword: 'state "[H*]"',
    defaultColor: 'sand',
    width: 34,
    height: 34,
    defaultData: { isDeep: true }
  },
  {
    id: 'act-state',
    label: 'State Machine State',
    nodeType: 'state',
    icon: 'Square',
    category: 'activity-state',
    categoryLabel: 'Activity & State Workflow',
    description: 'State machine state with rounded corners',
    plantumlKeyword: 'state',
    defaultColor: 'sand',
    width: 190,
    height: 90,
    shape: 'state',
    defaultData: {}
  },
  {
    id: 'act-state-composite',
    label: 'State with Actions',
    nodeType: 'state',
    icon: 'ListChecks',
    category: 'activity-state',
    categoryLabel: 'Activity & State Workflow',
    description: 'State machine state with entry, do, and exit activities',
    plantumlKeyword: 'state',
    defaultColor: 'sand',
    width: 220,
    height: 110,
    shape: 'state',
    defaultData: {
      attributes: [
        'entry / initializeContext()',
        'do / processWorkPayload()',
        'exit / flushAndClose()'
      ]
    }
  },
  {
    id: 'act-usecase',
    label: 'Use Case (Oval)',
    nodeType: 'usecase',
    icon: 'CircleDot',
    category: 'activity-state',
    categoryLabel: 'Activity & State Workflow',
    description: 'UML Use Case oval/ellipse',
    plantumlKeyword: 'usecase',
    defaultColor: 'sand',
    width: 180,
    height: 80,
    shape: 'usecase',
    defaultData: {}
  },

  // ==================== 6. ACTORS, PEOPLE & AGENTS ====================
  {
    id: 'actor-human',
    label: 'Actor (Stick-man)',
    nodeType: 'actor',
    icon: 'User',
    category: 'actor-agent',
    categoryLabel: 'Actors, People & Agents',
    description: 'Human end-user or system administrator',
    plantumlKeyword: 'actor',
    defaultColor: 'sand',
    width: 140,
    height: 90,
    shape: 'actor',
    defaultData: {}
  },
  {
    id: 'actor-agent',
    label: 'Autonomous Agent / Bot',
    nodeType: 'agent',
    icon: 'Bot',
    category: 'actor-agent',
    categoryLabel: 'Actors, People & Agents',
    description: 'Automated background process, bot, or AI agent',
    plantumlKeyword: 'agent',
    defaultColor: 'sage',
    width: 170,
    height: 80,
    shape: 'agent',
    defaultData: {}
  },

  // ==================== 7. C4 ARCHITECTURE MODEL ====================
  {
    id: 'c4-person',
    label: 'Person (C4 Level 1)',
    nodeType: 'c4-person',
    icon: 'User',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'Person(alias, label, desc) C4 Context actor',
    plantumlKeyword: 'Person',
    defaultColor: 'sienna',
    width: 200,
    height: 110,
    sublabel: '<<Person>>',
    shape: 'rectangle',
    defaultData: { c4Type: 'person', role: 'Customer', description: 'Buys items online' }
  },
  {
    id: 'c4-system',
    label: 'Software System (C4)',
    nodeType: 'c4-system',
    icon: 'Layers',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'System(alias, label, desc) Core software system',
    plantumlKeyword: 'System',
    defaultColor: 'slate',
    width: 220,
    height: 120,
    sublabel: '<<System>>',
    shape: 'rectangle',
    defaultData: { c4Type: 'system', description: 'Core e-commerce platform' }
  },
  {
    id: 'c4-container',
    label: 'Container App/Service (C4)',
    nodeType: 'c4-container',
    icon: 'Cpu',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'Container(alias, label, tech, desc) Web app, API, or DB',
    plantumlKeyword: 'Container',
    defaultColor: 'ochre',
    width: 220,
    height: 120,
    sublabel: '<<Container>>',
    shape: 'rectangle',
    defaultData: { c4Type: 'container', technology: 'Go / GraphQL', description: 'Order processing engine' }
  },
  {
    id: 'c4-component',
    label: 'Component (C4 Level 3)',
    nodeType: 'c4-component',
    icon: 'Box',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'Component(alias, label, tech, desc) Controller or service component',
    plantumlKeyword: 'Component',
    defaultColor: 'ochre',
    width: 220,
    height: 120,
    sublabel: '<<Component>>',
    shape: 'rectangle',
    defaultData: { c4Type: 'component', technology: 'TypeScript', description: 'Business rules engine' }
  },
  {
    id: 'c4-person-ext',
    label: 'External Person (C4)',
    nodeType: 'c4-person-ext',
    icon: 'User',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'Person_Ext(alias, label, desc) External third-party user',
    plantumlKeyword: 'Person_Ext',
    defaultColor: 'slate',
    width: 200,
    height: 110,
    sublabel: '<<External Person>>',
    shape: 'rectangle',
    defaultData: { c4Type: 'person-ext', description: 'Third-party auditor or vendor' }
  },
  {
    id: 'c4-system-ext',
    label: 'External System (C4)',
    nodeType: 'c4-system-ext',
    icon: 'Layers',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'System_Ext(alias, label, desc) External payment gateway or SaaS',
    plantumlKeyword: 'System_Ext',
    defaultColor: 'slate',
    width: 220,
    height: 120,
    sublabel: '<<External System>>',
    shape: 'rectangle',
    defaultData: { c4Type: 'system-ext', description: 'Third-party credit card gateway' }
  },
  {
    id: 'c4-system-db',
    label: 'System Database (C4)',
    nodeType: 'c4-system-db',
    icon: 'Database',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'SystemDb(alias, label, desc) System-level relational or document database',
    plantumlKeyword: 'SystemDb',
    defaultColor: 'slate',
    width: 220,
    height: 120,
    sublabel: '<<SystemDb>>',
    shape: 'cylinder',
    defaultData: { c4Type: 'system-db', description: 'Stores user accounts and transaction history' }
  },
  {
    id: 'c4-system-queue',
    label: 'System Queue (C4)',
    nodeType: 'c4-system-queue',
    icon: 'List',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'SystemQueue(alias, label, desc) System message queue or event bus',
    plantumlKeyword: 'SystemQueue',
    defaultColor: 'slate',
    width: 220,
    height: 110,
    sublabel: '<<SystemQueue>>',
    shape: 'queue',
    defaultData: { c4Type: 'system-queue', description: 'System-wide event bus' }
  },
  {
    id: 'c4-container-db',
    label: 'Container Database (C4)',
    nodeType: 'c4-container-db',
    icon: 'Database',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'ContainerDb(alias, label, tech, desc) Container database store',
    plantumlKeyword: 'ContainerDb',
    defaultColor: 'ochre',
    width: 220,
    height: 120,
    sublabel: '<<ContainerDb>>',
    shape: 'cylinder',
    defaultData: { c4Type: 'container-db', technology: 'PostgreSQL', description: 'Relational data store' }
  },
  {
    id: 'c4-container-queue',
    label: 'Container Queue (C4)',
    nodeType: 'c4-container-queue',
    icon: 'List',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'ContainerQueue(alias, label, tech, desc) Container message broker',
    plantumlKeyword: 'ContainerQueue',
    defaultColor: 'ochre',
    width: 220,
    height: 110,
    sublabel: '<<ContainerQueue>>',
    shape: 'queue',
    defaultData: { c4Type: 'container-queue', technology: 'Kafka / RabbitMQ', description: 'Asynchronous event pipeline' }
  },
  {
    id: 'c4-component-db',
    label: 'Component Database (C4)',
    nodeType: 'c4-component-db',
    icon: 'Database',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'ComponentDb(alias, label, tech, desc) Component-level data layer',
    plantumlKeyword: 'ComponentDb',
    defaultColor: 'ochre',
    width: 220,
    height: 120,
    sublabel: '<<ComponentDb>>',
    shape: 'cylinder',
    defaultData: { c4Type: 'component-db', technology: 'Redis / SQLite', description: 'In-memory component cache' }
  },
  {
    id: 'c4-deployment-node',
    label: 'Deployment Node (C4)',
    nodeType: 'c4-deployment-node',
    icon: 'Server',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'Deployment_Node(alias, label, type) Physical or virtual deployment host',
    plantumlKeyword: 'Deployment_Node',
    defaultColor: 'slate',
    width: 240,
    height: 130,
    sublabel: '<<deployment_node>>',
    shape: 'node3d',
    defaultData: { c4Type: 'deployment-node', role: 'Ubuntu Linux / Docker Engine' }
  },
  {
    id: 'c4-boundary-system',
    label: 'System Boundary (C4)',
    nodeType: 'c4-boundary',
    icon: 'Square',
    category: 'c4',
    categoryLabel: 'C4 Architecture Model',
    description: 'System_Boundary(alias, label) Groups internal containers & components',
    plantumlKeyword: 'System_Boundary',
    defaultColor: 'slate',
    width: 400,
    height: 280,
    sublabel: '<<System Boundary>>',
    shape: 'rectangle',
    defaultData: { c4Type: 'boundary', isContainer: true }
  },

  // ==================== ARCHIMATE ENTERPRISE ====================
  {
    id: 'archimate-strat-capability',
    label: 'Capability (Strategy)',
    nodeType: 'archimate-element',
    icon: 'Target',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Strategy layer business capability (#F5DEAA)',
    plantumlKeyword: 'Strategy_Capability',
    defaultColor: 'ochre',
    width: 210,
    height: 90,
    sublabel: '<<strategy-capability>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'strategy', archimateElement: 'capability' }
  },
  {
    id: 'archimate-strat-valuestream',
    label: 'Value Stream (Strategy)',
    nodeType: 'archimate-element',
    icon: 'TrendingUp',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Value stream delivering stakeholder outcomes (#F5DEAA)',
    plantumlKeyword: 'Strategy_ValueStream',
    defaultColor: 'ochre',
    width: 220,
    height: 90,
    sublabel: '<<strategy-valuestream>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'strategy', archimateElement: 'valuestream' }
  },
  {
    id: 'archimate-biz-actor',
    label: 'Business Actor (ArchiMate)',
    nodeType: 'archimate-element',
    icon: 'User',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Business layer actor or role (#FFFFB5)',
    plantumlKeyword: 'Business_Actor',
    defaultColor: 'ochre',
    width: 200,
    height: 90,
    sublabel: '<<business-actor>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'business', archimateElement: 'actor' }
  },
  {
    id: 'archimate-biz-process',
    label: 'Business Process',
    nodeType: 'archimate-element',
    icon: 'GitCommit',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Sequence of business behaviors (#FFFFB5)',
    plantumlKeyword: 'Business_Process',
    defaultColor: 'ochre',
    width: 220,
    height: 90,
    sublabel: '<<business-process>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'business', archimateElement: 'process' }
  },
  {
    id: 'archimate-biz-service',
    label: 'Business Service (ArchiMate)',
    nodeType: 'archimate-element',
    icon: 'Layers',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Customer-facing business service (#FFFFB5)',
    plantumlKeyword: 'Business_Service',
    defaultColor: 'ochre',
    width: 220,
    height: 90,
    sublabel: '<<business-service>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'business', archimateElement: 'service' }
  },
  {
    id: 'archimate-biz-object',
    label: 'Business Object',
    nodeType: 'archimate-element',
    icon: 'FileText',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Passive business information concept (#FFFFB5)',
    plantumlKeyword: 'Business_Object',
    defaultColor: 'ochre',
    width: 200,
    height: 90,
    sublabel: '<<business-object>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'business', archimateElement: 'object' }
  },
  {
    id: 'archimate-app-component',
    label: 'Application Component',
    nodeType: 'archimate-element',
    icon: 'Cpu',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Application layer component (#B5FFFF)',
    plantumlKeyword: 'Application_Component',
    defaultColor: 'sage',
    width: 220,
    height: 90,
    sublabel: '<<application-component>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'application', archimateElement: 'component' }
  },
  {
    id: 'archimate-app-interface',
    label: 'Application Interface',
    nodeType: 'archimate-element',
    icon: 'Share2',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Application access point or API (#B5FFFF)',
    plantumlKeyword: 'Application_Interface',
    defaultColor: 'sage',
    width: 210,
    height: 90,
    sublabel: '<<application-interface>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'application', archimateElement: 'interface' }
  },
  {
    id: 'archimate-app-service',
    label: 'Application Service',
    nodeType: 'archimate-element',
    icon: 'Zap',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Explicitly defined application service functionality (#B5FFFF)',
    plantumlKeyword: 'Application_Service',
    defaultColor: 'sage',
    width: 220,
    height: 90,
    sublabel: '<<application-service>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'application', archimateElement: 'service' }
  },
  {
    id: 'archimate-tech-node',
    label: 'Technology Node',
    nodeType: 'archimate-element',
    icon: 'Server',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Technology infrastructure node (#C9E7B7)',
    plantumlKeyword: 'Technology_Node',
    defaultColor: 'sage',
    width: 220,
    height: 90,
    sublabel: '<<technology-node>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'technology', archimateElement: 'node' }
  },
  {
    id: 'archimate-tech-device',
    label: 'Technology Device',
    nodeType: 'archimate-element',
    icon: 'HardDrive',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Physical IT hardware resource (#C9E7B7)',
    plantumlKeyword: 'Technology_Device',
    defaultColor: 'sage',
    width: 210,
    height: 90,
    sublabel: '<<technology-device>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'technology', archimateElement: 'device' }
  },
  {
    id: 'archimate-motivation-goal',
    label: 'Motivation Goal',
    nodeType: 'archimate-element',
    icon: 'Target',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Strategic motivation statement or goal (#CCCCFF)',
    plantumlKeyword: 'Motivation_Goal',
    defaultColor: 'slate',
    width: 210,
    height: 90,
    sublabel: '<<motivation-goal>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'motivation', archimateElement: 'goal' }
  },
  {
    id: 'archimate-impl-workpackage',
    label: 'Implementation Work Package',
    nodeType: 'archimate-element',
    icon: 'Package',
    category: 'archimate',
    categoryLabel: 'ArchiMate Enterprise',
    description: 'Project deliverable or milestone work package (#FFE0E0)',
    plantumlKeyword: 'Implementation_WorkPackage',
    defaultColor: 'sand',
    width: 230,
    height: 90,
    sublabel: '<<implementation-workpackage>>',
    shape: 'rectangle',
    defaultData: { archimateLayer: 'implementation', archimateElement: 'workpackage' }
  },

  // ==================== 8. CLOUD INFRASTRUCTURE LIBS ====================
  {
    id: 'cloud-aws-compute',
    label: 'AWS EC2 / Lambda',
    nodeType: 'cloud-aws',
    icon: 'Cloud',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'Amazon Web Services compute workload',
    plantumlKeyword: 'cloud',
    defaultColor: 'sienna',
    width: 190,
    height: 80,
    sublabel: '<<AWS EC2>>',
    shape: 'rectangle',
    defaultData: { cloudProvider: 'aws', cloudService: 'EC2', awsCategory: 'compute' }
  },
  {
    id: 'cloud-aws-rds',
    label: 'AWS RDS / Aurora',
    nodeType: 'cloud-aws',
    icon: 'Database',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'Amazon Relational Database Service',
    plantumlKeyword: 'database',
    defaultColor: 'ochre',
    width: 190,
    height: 80,
    sublabel: '<<AWS RDS>>',
    shape: 'cylinder',
    defaultData: { cloudProvider: 'aws', cloudService: 'RDS', awsCategory: 'database' }
  },
  {
    id: 'cloud-aws-s3',
    label: 'AWS S3 Bucket',
    nodeType: 'cloud-aws',
    icon: 'HardDrive',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'Amazon Simple Storage Service object store',
    plantumlKeyword: 'storage',
    defaultColor: 'sand',
    width: 190,
    height: 80,
    sublabel: '<<AWS S3>>',
    shape: 'horiz-cylinder',
    defaultData: { cloudProvider: 'aws', cloudService: 'S3', awsCategory: 'storage' }
  },
  {
    id: 'cloud-gcp-run',
    label: 'GCP Cloud Run',
    nodeType: 'cloud-gcp',
    icon: 'Cloud',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'Google Cloud managed serverless container',
    plantumlKeyword: 'cloud',
    defaultColor: 'sage',
    width: 190,
    height: 80,
    sublabel: '<<GCP Cloud Run>>',
    shape: 'rectangle',
    defaultData: { cloudProvider: 'gcp', cloudService: 'Cloud Run' }
  },
  {
    id: 'cloud-k8s-pod',
    label: 'Kubernetes Pod',
    nodeType: 'cloud-k8s',
    icon: 'Server',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'K8s core workload pod',
    plantumlKeyword: 'node',
    defaultColor: 'slate',
    width: 180,
    height: 80,
    sublabel: '<<k8s Pod>>',
    shape: 'component',
    defaultData: { cloudProvider: 'k8s', cloudService: 'Pod' }
  },

  // ==================== AWS STDLIB (stdlib/aws) ====================
  {
    id: 'aws-lambda',
    label: 'AWS Lambda',
    nodeType: 'cloud-aws',
    icon: 'Zap',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'AWSLAMBDA(alias, label) Serverless function',
    plantumlKeyword: 'AWSLAMBDA',
    defaultColor: 'sienna',
    width: 200,
    height: 85,
    sublabel: '<<AWS Lambda>>',
    shape: 'rectangle',
    defaultData: { cloudProvider: 'aws', cloudService: 'Lambda', awsCategory: 'compute' }
  },
  {
    id: 'aws-dynamodb',
    label: 'Amazon DynamoDB',
    nodeType: 'cloud-aws',
    icon: 'Database',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'AMAZONDYNAMODB(alias, label) Managed NoSQL database',
    plantumlKeyword: 'AMAZONDYNAMODB',
    defaultColor: 'ochre',
    width: 200,
    height: 85,
    sublabel: '<<AWS DynamoDB>>',
    shape: 'cylinder',
    defaultData: { cloudProvider: 'aws', cloudService: 'DynamoDB', awsCategory: 'database' }
  },
  {
    id: 'aws-rds-db',
    label: 'Amazon RDS',
    nodeType: 'cloud-aws',
    icon: 'Database',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'AMAZONRDS(alias, label) Relational Database Service',
    plantumlKeyword: 'AMAZONRDS',
    defaultColor: 'ochre',
    width: 200,
    height: 85,
    sublabel: '<<AWS RDS>>',
    shape: 'cylinder',
    defaultData: { cloudProvider: 'aws', cloudService: 'RDS', awsCategory: 'database' }
  },
  {
    id: 'aws-s3-bucket',
    label: 'Amazon S3',
    nodeType: 'cloud-aws',
    icon: 'HardDrive',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'AMAZONS3(alias, label) Simple Storage Service bucket',
    plantumlKeyword: 'AMAZONS3',
    defaultColor: 'sand',
    width: 200,
    height: 85,
    sublabel: '<<AWS S3>>',
    shape: 'horiz-cylinder',
    defaultData: { cloudProvider: 'aws', cloudService: 'S3', awsCategory: 'storage' }
  },
  {
    id: 'aws-apigateway',
    label: 'Amazon API Gateway',
    nodeType: 'cloud-aws',
    icon: 'Share2',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'AMAZONAPIGATEWAY(alias, label) Managed REST/HTTP API endpoint',
    plantumlKeyword: 'AMAZONAPIGATEWAY',
    defaultColor: 'sienna',
    width: 210,
    height: 85,
    sublabel: '<<AWS API Gateway>>',
    shape: 'rectangle',
    defaultData: { cloudProvider: 'aws', cloudService: 'APIGateway', awsCategory: 'integration' }
  },
  {
    id: 'aws-sqs',
    label: 'Amazon SQS',
    nodeType: 'cloud-aws',
    icon: 'List',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'AMAZONSQS(alias, label) Simple Queue Service queue',
    plantumlKeyword: 'AMAZONSQS',
    defaultColor: 'sienna',
    width: 200,
    height: 85,
    sublabel: '<<AWS SQS>>',
    shape: 'queue',
    defaultData: { cloudProvider: 'aws', cloudService: 'SQS', awsCategory: 'integration' }
  },
  {
    id: 'aws-sns',
    label: 'Amazon SNS',
    nodeType: 'cloud-aws',
    icon: 'Radio',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'AMAZONSNS(alias, label) Simple Notification pub/sub topic',
    plantumlKeyword: 'AMAZONSNS',
    defaultColor: 'sienna',
    width: 200,
    height: 85,
    sublabel: '<<AWS SNS>>',
    shape: 'rectangle',
    defaultData: { cloudProvider: 'aws', cloudService: 'SNS', awsCategory: 'integration' }
  },
  {
    id: 'aws-cloudwatch',
    label: 'Amazon CloudWatch',
    nodeType: 'cloud-aws',
    icon: 'Activity',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'AMAZONCLOUDWATCH(alias, label) Metrics, logs and alarms',
    plantumlKeyword: 'AMAZONCLOUDWATCH',
    defaultColor: 'slate',
    width: 210,
    height: 85,
    sublabel: '<<AWS CloudWatch>>',
    shape: 'rectangle',
    defaultData: { cloudProvider: 'aws', cloudService: 'CloudWatch', awsCategory: 'management' }
  },
  {
    id: 'aws-kinesis',
    label: 'Amazon Kinesis',
    nodeType: 'cloud-aws',
    icon: 'TrendingUp',
    category: 'cloud',
    categoryLabel: 'Cloud Infrastructure Libs',
    description: 'AMAZONKINESIS(alias, label) Real-time streaming data',
    plantumlKeyword: 'AMAZONKINESIS',
    defaultColor: 'slate',
    width: 200,
    height: 85,
    sublabel: '<<AWS Kinesis>>',
    shape: 'rectangle',
    defaultData: { cloudProvider: 'aws', cloudService: 'Kinesis', awsCategory: 'analytics' }
  },

  // ==================== DOMAIN STORYTELLING (stdlib/DomainStory) ====================
  {
    id: 'domainstory-person',
    label: 'Person (Domain Story)',
    nodeType: 'domainstory-node',
    icon: 'User',
    category: 'domainstory',
    categoryLabel: 'Domain Storytelling',
    description: 'Person(alias, label) Human actor in domain storytelling',
    plantumlKeyword: 'Person',
    defaultColor: 'ochre',
    width: 180,
    height: 95,
    sublabel: '<<DomainStory Person>>',
    shape: 'actor',
    defaultData: { domainStoryType: 'person' }
  },
  {
    id: 'domainstory-group',
    label: 'Group (Domain Story)',
    nodeType: 'domainstory-node',
    icon: 'Users',
    category: 'domainstory',
    categoryLabel: 'Domain Storytelling',
    description: 'Group(alias, label) Group or department of domain actors',
    plantumlKeyword: 'Group',
    defaultColor: 'ochre',
    width: 190,
    height: 95,
    sublabel: '<<DomainStory Group>>',
    shape: 'rectangle',
    defaultData: { domainStoryType: 'group' }
  },
  {
    id: 'domainstory-system',
    label: 'System (Domain Story)',
    nodeType: 'domainstory-node',
    icon: 'Monitor',
    category: 'domainstory',
    categoryLabel: 'Domain Storytelling',
    description: 'System(alias, label) Software system interacting in domain',
    plantumlKeyword: 'System',
    defaultColor: 'slate',
    width: 200,
    height: 95,
    sublabel: '<<DomainStory System>>',
    shape: 'rectangle',
    defaultData: { domainStoryType: 'system' }
  },
  {
    id: 'domainstory-document',
    label: 'Document (Work Object)',
    nodeType: 'domainstory-node',
    icon: 'FileText',
    category: 'domainstory',
    categoryLabel: 'Domain Storytelling',
    description: 'Document(alias, label) Physical or digital document',
    plantumlKeyword: 'Document',
    defaultColor: 'sand',
    width: 180,
    height: 90,
    sublabel: '<<DomainStory Document>>',
    shape: 'file',
    defaultData: { domainStoryType: 'document' }
  },
  {
    id: 'domainstory-folder',
    label: 'Folder (Work Object)',
    nodeType: 'domainstory-node',
    icon: 'Folder',
    category: 'domainstory',
    categoryLabel: 'Domain Storytelling',
    description: 'Folder(alias, label) Dossier or case folder',
    plantumlKeyword: 'Folder',
    defaultColor: 'sand',
    width: 180,
    height: 90,
    sublabel: '<<DomainStory Folder>>',
    shape: 'folder',
    defaultData: { domainStoryType: 'folder' }
  },
  {
    id: 'domainstory-call',
    label: 'Call (Work Object)',
    nodeType: 'domainstory-node',
    icon: 'PhoneCall',
    category: 'domainstory',
    categoryLabel: 'Domain Storytelling',
    description: 'Call(alias, label) Telephone call interaction',
    plantumlKeyword: 'Call',
    defaultColor: 'ochre',
    width: 180,
    height: 85,
    sublabel: '<<DomainStory Call>>',
    shape: 'card',
    defaultData: { domainStoryType: 'call' }
  },
  {
    id: 'domainstory-email',
    label: 'Email (Work Object)',
    nodeType: 'domainstory-node',
    icon: 'Mail',
    category: 'domainstory',
    categoryLabel: 'Domain Storytelling',
    description: 'Email(alias, label) Email dispatch or notification',
    plantumlKeyword: 'Email',
    defaultColor: 'ochre',
    width: 180,
    height: 85,
    sublabel: '<<DomainStory Email>>',
    shape: 'card',
    defaultData: { domainStoryType: 'email' }
  },
  {
    id: 'domainstory-conversation',
    label: 'Conversation (Work Object)',
    nodeType: 'domainstory-node',
    icon: 'MessageSquare',
    category: 'domainstory',
    categoryLabel: 'Domain Storytelling',
    description: 'Conversation(alias, label) In-person dialogue or meeting',
    plantumlKeyword: 'Conversation',
    defaultColor: 'ochre',
    width: 190,
    height: 85,
    sublabel: '<<DomainStory Conversation>>',
    shape: 'card',
    defaultData: { domainStoryType: 'conversation' }
  },
  {
    id: 'domainstory-info',
    label: 'Info (Work Object)',
    nodeType: 'domainstory-node',
    icon: 'Info',
    category: 'domainstory',
    categoryLabel: 'Domain Storytelling',
    description: 'Info(alias, label) Raw data or verbal information',
    plantumlKeyword: 'Info',
    defaultColor: 'sand',
    width: 180,
    height: 85,
    sublabel: '<<DomainStory Info>>',
    shape: 'card',
    defaultData: { domainStoryType: 'info' }
  },
  {
    id: 'domainstory-boundary',
    label: 'Domain Boundary',
    nodeType: 'domainstory-node',
    icon: 'Square',
    category: 'domainstory',
    categoryLabel: 'Domain Storytelling',
    description: 'Boundary(alias, label) Scope or bounded context boundary',
    plantumlKeyword: 'Boundary',
    defaultColor: 'slate',
    width: 380,
    height: 260,
    sublabel: '<<DomainStory Boundary>>',
    shape: 'rectangle',
    defaultData: { domainStoryType: 'boundary', isContainer: true }
  },

  // ==================== AdaML ARCHITECTURE (stdlib/adaml) ====================
  {
    id: 'adaml-package-spec',
    label: 'Ada Package Spec',
    nodeType: 'adaml-node',
    icon: 'Code',
    category: 'adaml',
    categoryLabel: 'AdaML Architecture',
    description: 'begin_package_spec(name) Ada package specification',
    plantumlKeyword: 'begin_package_spec',
    defaultColor: 'sienna',
    width: 240,
    height: 120,
    sublabel: '<<ada_package_spec>>',
    shape: 'package',
    defaultData: { adamlType: 'package-spec' }
  },
  {
    id: 'adaml-subprogram',
    label: 'Ada Subprogram',
    nodeType: 'adaml-node',
    icon: 'Terminal',
    category: 'adaml',
    categoryLabel: 'AdaML Architecture',
    description: 'subprogram(name) Ada procedure or function subprogram',
    plantumlKeyword: 'subprogram',
    defaultColor: 'ochre',
    width: 220,
    height: 90,
    sublabel: '<<ada_subprogram>>',
    shape: 'rectangle',
    defaultData: { adamlType: 'subprogram' }
  },
  {
    id: 'adaml-package-body',
    label: 'Ada Package Body',
    nodeType: 'adaml-node',
    icon: 'Box',
    category: 'adaml',
    categoryLabel: 'AdaML Architecture',
    description: 'package(name) Ada package body implementation',
    plantumlKeyword: 'package',
    defaultColor: 'slate',
    width: 230,
    height: 110,
    sublabel: '<<ada_package_body>>',
    shape: 'package',
    defaultData: { adamlType: 'package-body' }
  },
  {
    id: 'adaml-agent',
    label: 'Ada Task / Agent',
    nodeType: 'adaml-node',
    icon: 'Cpu',
    category: 'adaml',
    categoryLabel: 'AdaML Architecture',
    description: 'agent(name) Concurrent Ada task or active agent',
    plantumlKeyword: 'agent',
    defaultColor: 'ochre',
    width: 200,
    height: 95,
    sublabel: '<<ada_task>>',
    shape: 'agent',
    defaultData: { adamlType: 'agent' }
  },
  {
    id: 'adaml-actor',
    label: 'Ada Actor',
    nodeType: 'adaml-node',
    icon: 'User',
    category: 'adaml',
    categoryLabel: 'AdaML Architecture',
    description: 'actor(name) External operator or pilot',
    plantumlKeyword: 'actor',
    defaultColor: 'slate',
    width: 180,
    height: 95,
    sublabel: '<<ada_actor>>',
    shape: 'actor',
    defaultData: { adamlType: 'actor' }
  },

  // ==================== 9. EMBEDDED SUB-ENGINES ====================
  {
    id: 'embed-salt',
    label: 'Salt GUI Wireframe',
    nodeType: 'embedded-salt',
    icon: 'AppWindow',
    category: 'embedded',
    categoryLabel: 'Embedded Sub-Engines',
    description: 'Embedded Salt UI dialog, buttons, and form inputs',
    plantumlKeyword: 'salt',
    defaultColor: 'sand',
    width: 220,
    height: 140,
    shape: 'card',
    defaultData: {
      embeddedType: 'salt',
      embeddedContent: '{\n  <b>Login Screen</b>\n  Username: | "admin"\n  Password: | "****"\n  [Submit] | [Cancel]\n}'
    }
  },
  {
    id: 'embed-ditaa',
    label: 'Ditaa ASCII Art',
    nodeType: 'embedded-ditaa',
    icon: 'Terminal',
    category: 'embedded',
    categoryLabel: 'Embedded Sub-Engines',
    description: 'Vectorized ASCII block diagram',
    plantumlKeyword: 'ditaa',
    defaultColor: 'slate',
    width: 220,
    height: 120,
    shape: 'card',
    defaultData: {
      embeddedType: 'ditaa',
      embeddedContent: '+--------+  TCP  +--------+\n| Client | ----> | Server |\n+--------+       +--------+'
    }
  },
  {
    id: 'embed-math',
    label: 'LaTeX / Math Formula',
    nodeType: 'embedded-math',
    icon: 'Sigma',
    category: 'embedded',
    categoryLabel: 'Embedded Sub-Engines',
    description: 'PlantUML <math> LaTeX mathematical notation',
    plantumlKeyword: 'math',
    defaultColor: 'sand',
    width: 240,
    height: 100,
    shape: 'card',
    defaultData: {
      embeddedType: 'math',
      mathFormula: 'P(x) = \\frac{1}{\\sigma \\sqrt{2\\pi}} e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}'
    }
  },
  {
    id: 'wbs-work-package',
    label: 'WBS Work Package',
    nodeType: 'wbs-node',
    icon: 'Layers',
    category: 'activity-state',
    categoryLabel: 'Activity & State Workflow',
    description: 'Work Breakdown Structure (@startwbs) work package',
    plantumlKeyword: 'wbs',
    defaultColor: 'slate',
    width: 200,
    height: 90,
    shape: 'card',
    defaultData: {
      wbsLevel: 2,
      wbsCode: '1.2.1',
      wbsProgress: 65
    }
  },

  // ==================== 10. ANNOTATIONS & NOTES ====================
  {
    id: 'note-sticky',
    label: 'Sticky Note',
    nodeType: 'note',
    icon: 'FileText',
    category: 'annotation',
    categoryLabel: 'Annotations & Notes',
    description: 'PlantUML note with folded dog-ear corner',
    plantumlKeyword: 'note',
    defaultColor: 'gold',
    width: 190,
    height: 85,
    shape: 'file',
    defaultData: {
      description: 'TLS 1.3 encryption enabled with strict mTLS authentication.'
    }
  },

  // ==================== 11. SEQUENCE & INTERACTIONS ====================
  // Lifeline Participants
  {
    id: 'seq-participant',
    label: 'Participant',
    nodeType: 'seq-participant',
    icon: 'Box',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Standard sequence lifeline participant box',
    plantumlKeyword: 'participant',
    defaultColor: 'sand',
    width: 140,
    height: 60,
    shape: 'rounded'
  },
  {
    id: 'seq-actor',
    label: 'Actor Lifeline',
    nodeType: 'seq-actor',
    icon: 'User',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Human user or external caller stickman lifeline',
    plantumlKeyword: 'actor',
    defaultColor: 'sienna',
    width: 100,
    height: 70,
    shape: 'actor'
  },
  {
    id: 'seq-database',
    label: 'Database Lifeline',
    nodeType: 'seq-database',
    icon: 'Database',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Database cylinder lifeline participant',
    plantumlKeyword: 'database',
    defaultColor: 'slate',
    width: 130,
    height: 65,
    shape: 'cylinder'
  },
  {
    id: 'seq-queue',
    label: 'Queue Lifeline',
    nodeType: 'seq-queue',
    icon: 'Server',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Message broker or asynchronous event stream lifeline',
    plantumlKeyword: 'queue',
    defaultColor: 'ochre',
    width: 130,
    height: 60,
    shape: 'queue'
  },
  {
    id: 'seq-boundary',
    label: 'Boundary Lifeline',
    nodeType: 'seq-boundary',
    icon: 'Shield',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'API gateway or system perimeter lifeline',
    plantumlKeyword: 'boundary',
    defaultColor: 'sage',
    width: 130,
    height: 60,
    shape: 'boundary'
  },
  {
    id: 'seq-control',
    label: 'Control Lifeline',
    nodeType: 'seq-control',
    icon: 'Layers',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Controller, coordinator or business logic manager',
    plantumlKeyword: 'control',
    defaultColor: 'terracotta',
    width: 130,
    height: 60,
    shape: 'control'
  },
  {
    id: 'seq-entity',
    label: 'Entity Lifeline',
    nodeType: 'seq-entity',
    icon: 'Box',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Domain entity or persistent data model lifeline',
    plantumlKeyword: 'entity',
    defaultColor: 'sand',
    width: 130,
    height: 60,
    shape: 'entity-circle'
  },
  {
    id: 'seq-collections',
    label: 'Collections Lifeline',
    nodeType: 'seq-collections',
    icon: 'Boxes',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Multi-instance or pooled worker cluster lifeline',
    plantumlKeyword: 'collections',
    defaultColor: 'slate',
    width: 130,
    height: 60,
    shape: 'collections'
  },

  // Interactions & Messages
  {
    id: 'seq-msg-sync',
    label: 'Sync Call (->)',
    nodeType: 'seq-msg-sync',
    icon: 'ArrowRight',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Synchronous blocking invocation (A -> B : request)',
    plantumlKeyword: '->',
    defaultColor: 'sienna',
    width: 180,
    height: 30
  },
  {
    id: 'seq-msg-reply',
    label: 'Return / Reply (-->)',
    nodeType: 'seq-msg-reply',
    icon: 'ArrowLeftRight',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Return or response dashed arrow (B --> A : response)',
    plantumlKeyword: '-->',
    defaultColor: 'slate',
    width: 180,
    height: 30
  },
  {
    id: 'seq-msg-async',
    label: 'Async Event (->>)',
    nodeType: 'seq-msg-async',
    icon: 'ArrowRight',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Non-blocking asynchronous message or event publish',
    plantumlKeyword: '->>',
    defaultColor: 'ochre',
    width: 180,
    height: 30
  },
  {
    id: 'seq-msg-self',
    label: 'Self Call / Loop',
    nodeType: 'seq-msg-self',
    icon: 'RotateCw',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Internal processing or recursive self-invocation',
    plantumlKeyword: '->',
    defaultColor: 'sage',
    width: 120,
    height: 40
  },

  // Fragments & Blocks
  {
    id: 'seq-block-alt',
    label: 'Alt Frame (Conditional)',
    nodeType: 'seq-block-alt',
    icon: 'GitBranch',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Alternative conditional branching (alt [condition] ... else ... end)',
    plantumlKeyword: 'alt',
    defaultColor: 'sand',
    width: 320,
    height: 120
  },
  {
    id: 'seq-block-opt',
    label: 'Opt Frame (Optional)',
    nodeType: 'seq-block-opt',
    icon: 'GitCommit',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Optional execution block executed only if condition met',
    plantumlKeyword: 'opt',
    defaultColor: 'sand',
    width: 320,
    height: 100
  },
  {
    id: 'seq-block-loop',
    label: 'Loop Frame',
    nodeType: 'seq-block-loop',
    icon: 'RefreshCw',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Repeated iteration loop (loop [items] ... end)',
    plantumlKeyword: 'loop',
    defaultColor: 'sand',
    width: 320,
    height: 100
  },
  {
    id: 'seq-block-par',
    label: 'Par Frame (Parallel)',
    nodeType: 'seq-block-par',
    icon: 'Columns',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Parallel concurrent execution branches (par ... also ... end)',
    plantumlKeyword: 'par',
    defaultColor: 'sand',
    width: 320,
    height: 120
  },
  {
    id: 'seq-block-critical',
    label: 'Critical Section',
    nodeType: 'seq-block-critical',
    icon: 'AlertCircle',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Thread-safe atomic critical section block',
    plantumlKeyword: 'critical',
    defaultColor: 'sand',
    width: 320,
    height: 100
  },
  {
    id: 'seq-block-group',
    label: 'Group Frame',
    nodeType: 'seq-block-group',
    icon: 'Folder',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'Custom logical grouping frame',
    plantumlKeyword: 'group',
    defaultColor: 'sand',
    width: 320,
    height: 100
  },
  {
    id: 'seq-note',
    label: 'Sequence Note',
    nodeType: 'seq-note',
    icon: 'FileText',
    category: 'sequence',
    categoryLabel: 'Sequence & Interactions',
    description: 'UML note attached over or beside sequence lifelines',
    plantumlKeyword: 'note over',
    defaultColor: 'gold',
    width: 160,
    height: 60
  }
];

export const COLOR_THEMES = [
  { id: 'sienna', name: 'Sienna Terracotta', hex: '#c2652a', border: '#e8a87c', bg: '#fcf6f2' },
  { id: 'terracotta', name: 'Deep Terracotta', hex: '#b34d28', border: '#e4957c', bg: '#faf0eb' },
  { id: 'ochre', name: 'Warm Ochre', hex: '#c48227', border: '#e8be77', bg: '#fbf7ee' },
  { id: 'sage', name: 'Earthy Sage', hex: '#587a5f', border: '#a0c4a8', bg: '#f1f6f2' },
  { id: 'slate', name: 'Steel Slate', hex: '#4f5e6b', border: '#9bb0c1', bg: '#f0f3f6' },
  { id: 'sand', name: 'Desert Sand', hex: '#8a7d6b', border: '#cfc6b8', bg: '#f8f6f2' },
  { id: 'gold', name: 'Amber Gold', hex: '#b8860b', border: '#ebd278', bg: '#fdfbee' },
];

export function getColorConfig(colorKey?: string) {
  let base = { hex: '#c2652a', bgHex: '#fcf6f2', borderHex: '#e8a87c', badgeHex: '#8f3b0e' };
  switch (colorKey) {
    case 'sienna':
      base = { hex: '#c2652a', bgHex: '#fcf6f2', borderHex: '#e8a87c', badgeHex: '#8f3b0e' };
      break;
    case 'terracotta':
      base = { hex: '#b34d28', bgHex: '#faf0eb', borderHex: '#e4957c', badgeHex: '#7a290d' };
      break;
    case 'ochre':
      base = { hex: '#c48227', bgHex: '#fbf7ee', borderHex: '#e8be77', badgeHex: '#8a5209' };
      break;
    case 'sage':
      base = { hex: '#587a5f', bgHex: '#f1f6f2', borderHex: '#a0c4a8', badgeHex: '#304c35' };
      break;
    case 'slate':
      base = { hex: '#4f5e6b', bgHex: '#f0f3f6', borderHex: '#9bb0c1', badgeHex: '#2b3944' };
      break;
    case 'sand':
      base = { hex: '#8a7d6b', bgHex: '#f8f6f2', borderHex: '#cfc6b8', badgeHex: '#524838' };
      break;
    case 'gold':
      base = { hex: '#b8860b', bgHex: '#fdfbee', borderHex: '#ebd278', badgeHex: '#755400' };
      break;
    default:
      base = { hex: '#c2652a', bgHex: '#fcf6f2', borderHex: '#e8a87c', badgeHex: '#8f3b0e' };
  }

  return {
    ...base,
    bg: base.bgHex,
    border: base.borderHex
  };
}
